### PR TITLE
Add quartz theme, modify ag-grid version to 31.0.1 and add properties to be allowed to use as function

### PR DESCRIPTION
**Pull request by sdidier-dev**
Changelog:
- Add quartz theme
- Modify ag-grid version to 31.0.1, only bug fixes
- Add properties:
  - `quickFilterParser` in GRID_MAYBE_FUNCTIONS
  - `quickFilterMatcher` in GRID_MAYBE_FUNCTIONS_NO_PARAMS
  - `numberFormatter` and `numberParser` in COLUMN_MAYBE_FUNCTIONS
- Move `predicate` from COLUMN_MAYBE_FUNCTIONS to COLUMN_MAYBE_FUNCTIONS_NO_PARAMS

### CODE REVIEW

**Comment by sdidier-dev** [comment]
Hi @BSd3v ! New PR ! 😁

**Comment by BSd3v** [comment]
Looks good. 

Make sure you do `npm run format`, it looks like this may encounter some linting issues.

**Comment by sdidier-dev** [comment]
Didn't know about that ! 😅

**Comment by BSd3v** [comment]
Sweet. 😁

**Pull request merged**
